---
# This task will install apache packages
- name: Install web packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items: "{{ apache_packages }}"

- name: Change www-data group
  user:
    name: "{{ apache_user }}"
    groups: "{{ apache_groups }}"
    uid: "{{ apache_uid }}"
  when: apache_change_user != false
