---

- name: Enable apache2 modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items: "{{ apache_modules }}"
  notify: restart apache
  
- name: Disable apache2 modules
  apache2_module:
    name: "{{ item }}"
    state: absent
  with_items: "{{ apache_disable_modules }}"
  when: apache_disable_modules is defined
  notify: restart apache