---
- name: mpm event optimized
  template:
    src: mpn_event.conf.j2
    dest: /etc/apache2/mods-available/mpm_event.conf
  notify:
    - stop apache2
    - start apache2
  with_items: "{{mpm_event}}"
  when: mpm_event is defined
