---

- name: Add a blank file for use as the index of the default vhost
  file:
    path: /var/www/index.html
    mode: 0644
    state: touch
  
- name: Show only the "Apache" product name rather than the full version
  replace:
    dest: /etc/apache2/conf-enabled/security.conf
    regexp: "^ServerTokens OS$"
    replace: "ServerTokens ProductOnly"

- name: Fix up previous servers that had been given "Minimal" ServerTokens
  replace:
    dest: /etc/apache2/conf-enabled/security.conf
    regexp: "^ServerTokens Minimal$"
    replace: "ServerTokens ProductOnly"
 
- name: Don't add a signature line to server-generated content
  replace:
    dest: /etc/apache2/conf-enabled/security.conf
    regexp: "^ServerSignature On$"
    replace: "ServerSignature Off"
