---

- name: Dissite apache2 defaults
  command: a2dissite {{ item }}
  with_items: "{{ apache_dissite }}"
  when: apache_dissite is defined
  notify: reload apache

- name: Add apache vhosts configurations
  template:
    src: ../templates/vhost.conf.j2
    dest: "/etc/apache2/sites-available/{{ item.server_name }}.conf"
    owner: root
    group: root
    mode: 644
  with_items: "{{ apache_vhost }}"
  notify: reload apache

- name: Ensure document root exists
  file:
    path: "{{ item.document_root }}"
    state: directory
    owner: "{{ apache_dir_owner }}"
    group: "{{ apache_dir_group }}"
    mode: "{{ apache_dir_mode }}"
  with_items: "{{ apache_vhost }}"
  when: apache_document_root != false

- name: Reload Apache2
  service:
    name: apache2
    state: reloaded
    enabled: yes
