---

- name: Check if any vhosts need to be disabled
  stat:
    path: "/etc/apache2/sites-enabled/{{item}}.conf"
  with_items: "{{ apache_dissite }}"
  register: ds

- name: Disable specified vhosts
  command: "a2dissite {{ item.1 }}"
  with_together:
    - "{{ ds.results }}"
    - "{{ apache_dissite }}"
  when: (item.1 is defined and item.0.stat.islnk is defined) and item.0.stat.islnk
  no_log: true # produces lots of unreadable gibberish otherwise
  notify: reload apache

- name: Write config for each Apache vhost
  template:
    src: "{{ apache_template_path }}/{{ apache_template_name }}"
    dest: "/etc/apache2/sites-available/{{ item.server_name }}.conf"
    owner: "{{ apache_vhost_owner }}"
    group: "{{ apache_vhost_group }}"
    mode: "{{ apache_vhost_mode }}"
  with_items: "{{ apache_vhost }}"
  notify: reload apache

- name: Ensure that the document root exists
  file:
    path: "{{ item.document_root }}"
    state: directory
    owner: "{{ apache_dir_owner }}"
    group: "{{ apache_dir_group }}"
    mode: "{{ apache_dir_mode }}"
  with_items: "{{ apache_vhost }}"
  when: apache_document_root != false
  notify: reload apache

- name: Check if any vhosts need to be enabled
  stat:
    path: "/etc/apache2/sites-enabled/{{item.server_name}}.conf"
  with_items: "{{ apache_vhost }}"
  register: es

- name: Enable apache sites
  command: "a2ensite {{ item.1.server_name }}"
  with_together:
    - "{{ es.results }}"
    - "{{ apache_vhost }}"
  when: item.1.server_name is defined and (item.0.stat.islnk is not defined or not item.0.stat.islnk)
  no_log: true # produces lots of unreadable gibberish otherwise
  notify: reload apache
