---
- name: reload apache
  service:
    name: apache2
    state: reloaded

- name: restart apache
  service:
    name: apache2
    state: restarted

- name: stop apache2
  service:
    name: apache2
    state: stopped

- name: start apache2
  service:
    name: apache2
    state: started
